[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["scraping"]
scraping = ["metro-scrape"]
tectonic = ["dep:tectonic", "tectonic_bundles"]

[dependencies]
axum = { version = "0.6.16" }
eyre = "0.6.8"
num = "0.4.0"
dotenv = "0.15.0"
sqlx = { version = "0.6", features = [
	"postgres",
	"macros",
	"migrate",
	"uuid",
	"runtime-tokio-rustls",
	"offline",
	"bigdecimal",
	"time",
	"chrono",
] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
metro-scrape = { path = "../metro-scrape", optional = true }
chrono = { version = "*", features = ["serde"] }
log = "0.4"
regex = "*"
tectonic = { version = "0.13.1", optional = true }
tectonic_bundles = { version = "0.3.0", optional = true }
bigdecimal = { version = "0.3", features = ["serde"] }
tower-http = { version = "*", features = ["cors", "fs", "trace"] }
rust-embed = { version = "*", features = ["axum"] }
mime_guess = "2"
axum-login = { version = "0.5.0", features = ["sqlx", "postgres"] }
time-macros = { version = "0.2.10", features = ["parsing"] }
time = { version = "0.3.23", features = ["serde"] }
rand = { version = "0.8.5", features = ["min_const_gen"] }
fern = { version = "0.6.2", features = ["colored"] }
axum-htmx = "0.4.0"
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.3.0"
maud = { version = "0.25.0", features = ["axum"] }
