[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = ["scraping"]
scraping = ["metro-scrape"]
tectonic = ["dep:tectonic", "tectonic_bundles"]

[dependencies]
axum = "0.6.16"
eyre = "0.6.8"
num = "0.4.0"
sqlx = { version = "0.5.13", features = ["postgres", "macros", "migrate", "uuid", "runtime-tokio-rustls", "offline", "bigdecimal", "time"]}
tokio = { version = "1", features = ["full"] }
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
metro-scrape = {path = "../metro-scrape", optional = true}
chrono = "*"
log = "0.4"
regex = "*"
tectonic = {version = "0.12.0", optional = true}
tectonic_bundles = { version = "0.3.0", optional = true }

