[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.5"
dotenv.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.117"
tokio = { workspace = true, features = ["full"] }
